services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/code
    depends_on:
     - db

  db:
    image: postgres:15.4
    volumes:
      - postgres-data-155
    environment:
      - POSTGRES_USER=iniad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb

  nginx:
    image: nginx:latest
    container_name: mynginx-155
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres-data-155: